# SPDX-FileCopyrightText: 2023 Stefano Volpe <foxy@teapot.ovh>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: JSON check

on:
  push:
    paths:
      - "**/*.json"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check JSON syntax
        uses: limitusus/json-syntax-check@v2
        with:
          pattern: "\\.json$"
      - name: Check JSON formatting
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.json
          only_changed: True
